### ISSUE TITLE
 fastapi with Python programming model v2

### ISSUE THREAD

**Issue by davide-bontempelli-zupit** [Azure-Samples/fastapi-on-azure-functions#18]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Is it possible to use fastapi with Python programming model v2? I can not find any information about this

**Comment by pamelafox** [comment]
@davide-bontempelli-zupit I've made a PR to update this sample to v2:
https://github.com/Azure-Samples/fastapi-on-azure-functions/pull/21

**Comment by pamelafox** [comment]
The PR was merged, this issue can now be closed. @shreyabatra4

**Comment by davide-bontempelli-zupit** [comment]
Closing since it was merged
