### ISSUE TITLE
Updating/work-with this template for GHA and Azd Devcontainer feature.

### ISSUE THREAD

**Issue by zedy-wj** [Azure-Samples/fastapi-on-azure-functions#24]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

We are updating this template to support new features in `Github Action` and `Azd Devcontainer`.

1. For the Github Action feature: We will remove two lines of code on container image and add GHA code after checkout step in the `.github/workflow/azure-dev.yml` file. (Shown as below)
<img width="302" alt="image" src="https://github.com/Azure-Samples/openai-plugin-fastapi/assets/81678720/b78e7045-08c4-4e09-90cd-ba0b22f50fe7">

2. For the Azd Devcontainer feature: We will add  the following code in `devcontainer.json` file.

``` 
"ghcr.io/azure/azure-dev/azd:latest": {}
``` 
And remove the relevant code for installing `azd` in `Dockerfile` under `.devcontainer` folder.
```
RUN curl -fsSL https://aka.ms/install-azd.sh | bash \
```

@rajeshkamal5050 , @pamelafox , @shreyabatra4 for notification.

**Comment by pamelafox** [comment]
FYI, I added azd feature in this PR here: 
https://github.com/Azure-Samples/fastapi-on-azure-functions/pull/23
